version: '3.8'

services:
    app:
        image: php:8.1-fpm
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel-network
        depends_on:
            - db

    web:
        image: nginx:alpine
        container_name: laravel_web
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network
        depends_on:
            - app

    db:
        image: postgres:15
        container_name: laravel_db
        environment:
            POSTGRES_USER: 'malixds'
            POSTGRES_PASSWORD: ''
            POSTGRES_DB: 'mireadb'
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - laravel-network

volumes:
    db_data:

networks:
    laravel-network:
